# TODO drop this file once FOSUserBundle has been refactored to provide finer validation groups
FOS\UserBundle\Model\User:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: emailCanonical
            errorPath: email
            message: fos_user.email.already_used
            groups: FullRegistration

    properties:
        email:
            - NotBlank:
                message: fos_user.email.blank
                groups: FullRegistration
            - MinLength:
                limit: 2
                message: fos_user.email.short
                groups: FullRegistration
            - MaxLength:
                limit: 254
                message: fos_user.email.long
                groups: FullRegistration
            - Email:
                message: fos_user.email.invalid
                groups: FullRegistration

        plainPassword:
            - NotBlank:
                message: fos_user.password.blank
                groups: FullRegistration
            - MinLength:
                limit: 2
                message: fos_user.password.short
                groups: FullRegistration
