imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: en }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        assets_version: 201209071855
    default_locale:  en
    trust_proxy_headers: false # Should Request object should trust proxy headers (X_FORWARDED_FOR/HTTP_CLIENT_IP)
    session:
        save_path: "%kernel.root_dir%/sessions/%kernel.environment%"

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    globals:
        kissmetrics_api_key: %kissmetrics_api_key%
        google_analytics_account: %google_analytics_account%
    form:
        resources:
            - 'MainBundle:Form:form.html.twig'

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:
        - FrontendBundle
        - MainBundle
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        lessphp: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true
        dql:
            numeric_functions:
                ifnull: HighFive\MainBundle\Doctrine\Query\IfNull

fos_js_routing:
    routes_to_expose:
        - "^api_.*"
        - "fos_user_security_logout"

fos_rest:
    routing_loader:
        default_format: json
    view:
        formats:
            json: true

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: HighFive\MainBundle\Entity\User
    service:
        mailer: high_five.mailer.fos_user
    resetting:
        email:
            template: MainBundle:Mail:passwordResetting.html.twig
    registration:
        form:
            type: high_five_registration
            handler: high_five.registration.form_handler
            validation_groups: ['FullRegistration']

hb_stampie:
    adapter: buzz
    mailer: mandrill
    server_token: %mandrill_api_key%
    extra:
        delivery_address: %mailer_delivery_address%

jms_serializer:
    handlers:
        avatar: ~
        datetime:
            default_timezone: UTC
    metadata:
        directories:
            - { path: %kernel.root_dir%/Resources/FOSUserBundle/serializer, namespace_prefix: 'FOS\UserBundle' }

knp_markdown:
    parser:
        service: high_five.markdown.parser

nelmio_api_doc:
    name: HighFive API

sensio_framework_extra:
    view:
        annotations: false
    request:
        converters: false
    cache:
        annotations: false
    router:
        annotations: false
