FrontendBundle:
    resource: "@FrontendBundle/Resources/config/routing.yml"

main:
    resource: "@MainBundle/Resources/config/routing/main.yml"

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /signup

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /password-recovery

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

bazinga_expose_translation:
    resource: "@BazingaExposeTranslationBundle/Resources/config/routing/routing.yml"
    prefix: /js

nelmio_api_doc:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

nelmio_js_logger:
    resource: "@NelmioJsLoggerBundle/Resources/config/routing.xml"
    prefix:   /nelmio-js-logger

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal

# replace the FOSUserBundle route to redirect to our own route
# TODO: change the way it is done once FOSUB provides an event to set the redirect response.
fos_user_registration_confirmed:
    pattern: /signup/confirmed
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: invitation_invite
        permanent: true
