<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120907132247 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("ALTER TABLE invitation ADD recipient_id INT NOT NULL, ADD resent_at DATETIME DEFAULT NULL");

        $this->addSql(<<<SQL
INSERT INTO users (organization_id, username, username_canonical, email, email_canonical, enabled, salt, password, locked, expired, roles, credentials_expired, first_name, last_name, points, given_points, received_points)
SELECT i.organization_id, i.email, LOWER(i.email), i.email, LOWER(i.email), 0, SHA1(CONCAT(RAND(), i.email)), '', 0, 0, 'a:0:{}', 0, '', '', 0, 0, 0
    FROM invitation i WHERE i.confirmed_at IS NULL
SQL
        );
        $this->addSql(<<<SQL
UPDATE invitation SET recipient_id = (SELECT u.id FROM users u WHERE u.email = invitation.email LIMIT 1)
SQL
        );

        $this->addSql("ALTER TABLE invitation DROP email");
        $this->addSql("ALTER TABLE invitation ADD CONSTRAINT FK_F11D61A2E92F8F78 FOREIGN KEY (recipient_id) REFERENCES users (id)");
        $this->addSql("CREATE UNIQUE INDEX UNIQ_F11D61A2E92F8F78 ON invitation (recipient_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("ALTER TABLE invitation DROP FOREIGN KEY FK_F11D61A2E92F8F78");
        $this->addSql("DROP INDEX UNIQ_F11D61A2E92F8F78 ON invitation");
        $this->addSql("ALTER TABLE invitation ADD email VARCHAR(255) NOT NULL");

        $this->addSql("UPDATE invitation SET email = (SELECT u.email FROM users u WHERE u.id = invitation.recipient_id)");
        $this->addSql("DELETE u FROM users u INNER JOIN invitation i ON i.recipient_id = u.id WHERE i.confirmed_at IS NULL");

        $this->addSql("ALTER TABLE invitation DROP recipient_id, DROP resent_at");
    }
}
