<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;
use HighFive\MainBundle\Entity\User;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120730144714 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("ALTER TABLE users ADD remainingPoints INT NOT NULL");
        $this->addSql("UPDATE users SET remainingPoints = ?", array(User::POINT_LIMIT));
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("ALTER TABLE users DROP remainingPoints");
    }
}
