<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;
use Doctrine\DBAL\Types\Type;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120829102915 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("ALTER TABLE users ADD received_points INT NOT NULL");
        $this->addSql(
            "UPDATE users SET received_points = (SELECT SUM(r.points) FROM recognition r WHERE r.recipient_id = users.id AND r.created_at > ?)",
            array(Type::getType('datetime')->convertToDatabaseValue(new \DateTime('midnight first day of this month'), $this->connection->getDatabasePlatform()))
        );
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("ALTER TABLE users DROP received_points");
    }
}
