<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;
use HighFive\MainBundle\Entity\User;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120827160750 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("ALTER TABLE users CHANGE remainingpoints given_points INT NOT NULL");
        $this->addSql("UPDATE users SET given_points = ? - given_points", array(User::POINT_LIMIT));
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("ALTER TABLE users CHANGE given_points remainingPoints INT NOT NULL");
        $this->addSql("UPDATE users SET remainingPoints = ? - remainingPoints", array(User::POINT_LIMIT));
    }
}
